In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st
import numpy as np
import sklearn.datasets as dta
import seaborn as sns
import seaborn.objects as so

In [2]:
#HYPOTHESIS

#1) Misha
    #Do hybrid types have more happy effects compared to non-hybrid types?
        #Option 1: Create data frame from first 5 columns, then call columns needed to compare type with effect

    #Option 2: Group data by type and effect

    #Visual display of how many happy effects associated to each type - Donut Charts (3 total)
    
    #What is the correlation of type to effect-Use P-Values - Scatter Plot
        #Make sure to add statement - If P value is greater than x-value (look for this) there is a strong correlation

#2) Kim
    #Does sweet profile cannabis have a higher rating?
        #What Flavor had the Max Rating
        #What Flavor has the min Rating
        #What Flavor has the median Rating
    
#3) #Latti
    #Does the location of the breeder impact the rating? Does the location impact the type that is grown?


#4)  Tacha
    #Is there a significant difference in the effects experienced by consumers when they rate the same cannabis type differently? 
    #(Use data to get the ratings of the cannabis type and analyze the effects reported to see if they are consistent.) Do users feel different effects when they use the same type of cannabis(yes). How does this affect how they rate it? Ex: Hybrid- 13 users said it made them aroused. What is the average rating reported by those 13 people? Repeat for a few more effects in Hybrid, Sativa, then Indica.

In [3]:
Original_Data = pd.read_csv("new_data.csv",encoding ='latin-1')
Original_Data.head()

,Strain,Type,Rating,Effects,Flavor,Breeders,LOCATION
0,1024,sativa,4.4,"Uplifted,Happy,Relaxed,Energetic,Creative","Spicy/Herbal,Sage,Woody",Medical Seeds Co,Spain
1,100-Og,hybrid,4.0,"Creative,Energetic,Tingly,Euphoric,Relaxed","Earthy,Sweet,Citrus",NaN,NaN
2,13-Dawgs,hybrid,4.2,"Tingly,Creative,Hungry,Relaxed,Uplifted","Apricot,Citrus,Grapefruit",Canadian LP Delta 9 BioTech,Canada
3,24K-Gold,hybrid,4.6,"Happy,Relaxed,Euphoric,Uplifted,Talkative","Citrus,Earthy,Orange",NaN,Los Angeles
4,3-Bears-Og,indica,0.0,NaN,NaN,Mephisto Genetics,NaN

In [4]:
Original_Data.Effects.str.split(",",expand=True)

             0          1          2          3          4
0     Uplifted      Happy    Relaxed  Energetic   Creative
1     Creative  Energetic     Tingly   Euphoric    Relaxed
2       Tingly   Creative     Hungry    Relaxed   Uplifted
3        Happy    Relaxed   Euphoric   Uplifted  Talkative
4          NaN        NaN        NaN        NaN        NaN
...        ...        ...        ...        ...        ...
2346     Happy   Uplifted    Relaxed   Euphoric  Energetic
2347   Relaxed      Happy   Euphoric   Uplifted     Sleepy
2348   Relaxed     Sleepy  Talkative   Euphoric      Happy
2349   Relaxed     Sleepy   Euphoric      Happy     Hungry
2350    Hungry    Relaxed   Uplifted      Happy     Sleepy

[2351 rows x 5 columns]

In [5]:
effects = Original_Data.Effects.str.split(",",expand=True)
effects.columns=["effect_1", "effect_2", "effect_3", "effect_4", "effect_5"]
effects.head()

   effect_1   effect_2  effect_3   effect_4   effect_5
0  Uplifted      Happy   Relaxed  Energetic   Creative
1  Creative  Energetic    Tingly   Euphoric    Relaxed
2    Tingly   Creative    Hungry    Relaxed   Uplifted
3     Happy    Relaxed  Euphoric   Uplifted  Talkative
4       NaN        NaN       NaN        NaN        NaN

In [6]:
flavors = Original_Data.Flavor.str.split(",",expand=True)
flavors.columns=["flavor_1", "flavor_2", "flavor_3", "flavor_4"]
flavors.head()

       flavor_1 flavor_2    flavor_3 flavor_4
0  Spicy/Herbal     Sage       Woody     None
1        Earthy    Sweet      Citrus     None
2       Apricot   Citrus  Grapefruit     None
3        Citrus   Earthy      Orange     None
4           NaN      NaN         NaN      NaN

In [7]:
flavors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2351 entries, 0 to 2350
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   flavor_1  2195 non-null   object
 1   flavor_2  2161 non-null   object
 2   flavor_3  2117 non-null   object
 3   flavor_4  43 non-null     object
dtypes: object(4)
memory usage: 73.6+ KB

In [8]:
pd.concat([Original_Data, effects, flavors], axis=1)

,Strain,Type,Rating,Effects,Flavor,Breeders,LOCATION,effect_1,effect_2,effect_3,effect_4,effect_5,flavor_1,flavor_2,flavor_3,flavor_4
0,1024,sativa,4.4,"Uplifted,Happy,Relaxed,Energetic,Creative","Spicy/Herbal,Sage,Woody",Medical Seeds Co,Spain,Uplifted,Happy,Relaxed,Energetic,Creative,Spicy/Herbal,Sage,Woody,None
1,100-Og,hybrid,4.0,"Creative,Energetic,Tingly,Euphoric,Relaxed","Earthy,Sweet,Citrus",NaN,NaN,Creative,Energetic,Tingly,Euphoric,Relaxed,Earthy,Sweet,Citrus,None
2,13-Dawgs,hybrid,4.2,"Tingly,Creative,Hungry,Relaxed,Uplifted","Apricot,Citrus,Grapefruit",Canadian LP Delta 9 BioTech,Canada,Tingly,Creative,Hungry,Relaxed,Uplifted,Apricot,Citrus,Grapefruit,None
3,24K-Gold,hybrid,4.6,"Happy,Relaxed,Euphoric,Uplifted,Talkative","Citrus,Earthy,Orange",NaN,Los Angeles,Happy,Relaxed,Euphoric,Uplifted,Talkative,Citrus,Earthy,Orange,None
4,3-Bears-Og,indica,0.0,NaN,NaN,Mephisto Genetics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2346,Zeus-Og,hybrid,4.7,"Happy,Uplifted,Relaxed,Euphoric,Energetic","Earthy,Woody,Pine",A Greener Today's Dankczar,NaN,Happy,Uplifted,Relaxed,Euphoric,Energetic,Earthy,Woody,Pine,None
2347,Zkittlez,indica,4.6,"Relaxed,Happy,Euphoric,Uplifted,Sleepy","Sweet,Berry,Grape",3rd Gen Family and Terp Hogz,NaN,Relaxed,Happy,Euphoric,Uplifted,Sleepy,Sweet,Berry,Grape,None
2348,Zombie-Kush,indica,5.0,"Relaxed,Sleepy,Talkative,Euphoric,Happy","Earthy,Sweet,Spicy/Herbal",Ripper Seeds,NaN,Relaxed,Sleepy,Talkative,Euphoric,Happy,Earthy,Sweet,Spicy/Herbal,None
2349,Zombie-Og,indica,4.4,"Relaxed,Sleepy,Euphoric,Happy,Hungry","Sweet,Earthy,Pungent",NaN,NaN,Relaxed,Sleepy,Euphoric,Happy,Hungry,Sweet,Earthy,Pungent,None
2350,Zoom-Pie,indica,4.6,"Hungry,Relaxed,Uplifted,Happy,Sleepy","Berry,Earthy,Pungent",NaN,NaN,Hungry,Relaxed,Uplifted,Happy,Sleepy,Berry,Earthy,Pungent,None

In [9]:
#Clean original data and combined data frame of the flavors and effects into the original Data Frame
OD2=pd.concat([Original_Data, effects, flavors], axis=1)
OD2.head()

,Strain,Type,Rating,Effects,Flavor,Breeders,LOCATION,effect_1,effect_2,effect_3,effect_4,effect_5,flavor_1,flavor_2,flavor_3,flavor_4
0,1024,sativa,4.4,"Uplifted,Happy,Relaxed,Energetic,Creative","Spicy/Herbal,Sage,Woody",Medical Seeds Co,Spain,Uplifted,Happy,Relaxed,Energetic,Creative,Spicy/Herbal,Sage,Woody,None
1,100-Og,hybrid,4.0,"Creative,Energetic,Tingly,Euphoric,Relaxed","Earthy,Sweet,Citrus",NaN,NaN,Creative,Energetic,Tingly,Euphoric,Relaxed,Earthy,Sweet,Citrus,None
2,13-Dawgs,hybrid,4.2,"Tingly,Creative,Hungry,Relaxed,Uplifted","Apricot,Citrus,Grapefruit",Canadian LP Delta 9 BioTech,Canada,Tingly,Creative,Hungry,Relaxed,Uplifted,Apricot,Citrus,Grapefruit,None
3,24K-Gold,hybrid,4.6,"Happy,Relaxed,Euphoric,Uplifted,Talkative","Citrus,Earthy,Orange",NaN,Los Angeles,Happy,Relaxed,Euphoric,Uplifted,Talkative,Citrus,Earthy,Orange,None
4,3-Bears-Og,indica,0.0,NaN,NaN,Mephisto Genetics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
OD2["num_effects"]=OD2.Effects.str.count(",")+1
OD2["num_flavors"]=OD2.Flavor.str.count(",")+1
OD2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2351 entries, 0 to 2350
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Strain       2351 non-null   object
 1   Type         2351 non-null   object
 2   Rating       2351 non-null   float64
 3   Effects      2264 non-null   object
 4   Flavor       2195 non-null   object
 5   Breeders     1165 non-null   object
 6   LOCATION     614 non-null    object
 7   effect_1     2264 non-null   object
 8   effect_2     2254 non-null   object
 9   effect_3     2239 non-null   object
 10  effect_4     2212 non-null   object
 11  effect_5     2180 non-null   object
 12  flavor_1     2195 non-null   object
 13  flavor_2     2161 non-null   object
 14  flavor_3     2117 non-null   object
 15  flavor_4     43 non-null     object
 16  num_effects  2264 non-null   float64
 17  num_flavors  2195 non-null   float64
dtypes: float64(3), object(15)
memory usage: 330.7+ KB

In [11]:
OD2["effect_1"].value_counts()

effect_1
Relaxed      825
Happy        476
Euphoric     249
Uplifted     244
Sleepy        89
Creative      80
Energetic     74
Talkative     55
Focused       53
Aroused       38
Hungry        36
Tingly        32
Giggly        12
Dry            1
Name: count, dtype: int64

In [12]:
#Remove null values - Flavor4
OD2=OD2.drop(columns=["flavor_4"])
OD3=OD2.dropna(how="any")
OD3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 501 entries, 0 to 2341
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Strain       501 non-null    object
 1   Type         501 non-null    object
 2   Rating       501 non-null    float64
 3   Effects      501 non-null    object
 4   Flavor       501 non-null    object
 5   Breeders     501 non-null    object
 6   LOCATION     501 non-null    object
 7   effect_1     501 non-null    object
 8   effect_2     501 non-null    object
 9   effect_3     501 non-null    object
 10  effect_4     501 non-null    object
 11  effect_5     501 non-null    object
 12  flavor_1     501 non-null    object
 13  flavor_2     501 non-null    object
 14  flavor_3     501 non-null    object
 15  num_effects  501 non-null    float64
 16  num_flavors  501 non-null    float64
dtypes: float64(3), object(14)
memory usage: 70.5+ KB

In [13]:
#We droped 12% of null values so 88% of our data is valid
#(2351-2053)/2351

In [14]:
#fIND TOTAL VALUES FOR EACH TYPE
OD3.Type.value_counts()

Type
hybrid    236
indica    157
sativa    108
Name: count, dtype: int64

In [15]:
#Find average rating for each
OD3.groupby("Type").Rating.mean()

Type
hybrid    4.398305
indica    4.455414
sativa    4.435185
Name: Rating, dtype: float64

In [16]:
#COUNT FOR EACH EFFECT FOR EFFECT1 BY TYPE
OD3.groupby(["Type", "effect_1"]).size()

Type    effect_1
hybrid  Aroused        4
        Creative       6
        Energetic      4
        Euphoric      34
        Focused        7
        Happy         63
        Hungry         2
        Relaxed       74
        Sleepy         2
        Talkative      7
        Tingly         4
        Uplifted      29
indica  Aroused        2
        Creative       2
        Euphoric      15
        Focused        1
        Giggly         1
        Happy          8
        Hungry         1
        Relaxed      112
        Sleepy        10
        Talkative      1
        Uplifted       4
sativa  Aroused        3
        Creative       5
        Energetic      6
        Euphoric      21
        Focused        4
        Giggly         1
        Happy         31
        Hungry         1
        Relaxed        9
        Sleepy         1
        Talkative      2
        Uplifted      24
dtype: int64

In [17]:
#COUNT FOR EACH EFFECT FOR EFFECT2 BY TYPE
#OD3.groupby(["Type", "effect_2"]).size()

In [18]:
#COUNT FOR EACH EFFECT FOR EFFECT3 BY TYPE
#OD3.groupby(["Type", "effect_3"]).size()

In [19]:
#COUNT FOR EACH EFFECT FOR EFFECT4 BY TYPE
#OD3.groupby(["Type", "effect_4"]).size()

In [20]:
#COUNT FOR EACH EFFECT FOR EFFECT5 BY TYPE
#OD3.groupby(["Type", "effect_5"]).size()

In [21]:
#df3.to_csv("MaryJane_clean_data.csv", index=False)

In [22]:
#Remove null values - Breeders
# OD2=OD2.drop(columns=["Breeders"])
# OD3Breeders=OD2.dropna(how="any")
# OD3Breeders.info()

In [23]:
# Pull the list of The Top 5 Breeders
top5_breeders=list(OD2["Breeders"].value_counts().index[1:6])
top5_breeders

['DNA Genetics',
 'Colorado Seed Inc.',
 'Rare Dankness Seeds',
 "Barney's Farm",
 'Bodhi Seeds']

In [44]:
# Pull the list of The Top 50 Breeders
top50_breeders=list(OD2["Breeders"].value_counts().index[1:51])
top50_breeders

['DNA Genetics',
 'Colorado Seed Inc.',
 'Rare Dankness Seeds',
 "Barney's Farm",
 'Bodhi Seeds',
 'TGA Genetics',
 'Exotic Genetix',
 'Sensi Seeds',
 'Paradise Seeds',
 'Green House Seeds',
 'Dinafem Seeds',
 'Dutch Passion Seed Company',
 'Ace Seeds',
 'THSeeds',
 'Archive Seeds Bank',
 'Pua Mana 1st Hawaiian Pakal_l_ Seed Bank',
 'Tikum Olam',
 'AlphaKronic Genes',
 'MTG Seeds',
 'Flying Dutchman',
 'SinCity Seeds ',
 'Nirvana Seeds',
 'Calyx Garden',
 'Soma Sacred Seeds',
 'Mr Nice Seeds ',
 'Cresco Labs',
 'Jordan of the Islands',
 'Canadian LP Tweed, Inc',
 'TGA Subcool Genetics',
 'Royal Queen Seeds',
 'Sumo Seeds',
 'Elemental Seeds',
 'Alien Genetics',
 'THClones',
 'Delicious Seeds',
 'Royal Choice Farms',
 'Snow High Seeds',
 'Rebel Spirit Cannabis',
 'Dynasty Seeds',
 'Soulshine Cannabis',
 'Reeferman Seeds',
 'Terraform Genetics',
 'Apothecary Genetics',
 'Cali Connection',
 'Los Angeles Kush',
 'Leaf by Snoop',
 'OG Raskal Genetics',
 'Ocean Grown Seeds',
 'Serious Seed',
 'Heroes of the Farm GeneticsÊ']

In [43]:
# #Create a bar chart that shows the number of each type grown by Top 5 Breeders
# breeders_type=top5_breeders_df.groupby(['Breeders','Type'])['Type'].count().unstack()
# breeders_type.plot(kind='bar')
# ax.bar_label(ax.containers[0])
# plt.xlabel('Top 5 Breeders')
# plt.ylabel('Total Count of Types')
# plt.title('Total Count For The Top 5 Breeders')
# # ax.margins(y=1)
# plt.ylim(0, 24)
plt.show()

In [46]:
top5_breeders_df.groupby(['Breeders','Type','Strain'])[['Strain']].sum()

                                                                         Strain
Breeders            Type   Strain
Barney's Farm       hybrid Crimea-Blue                              Crimea-Blue
                           Lsd                                              Lsd
                           Morning-Glory                          Morning-Glory
                           Pineapple-Chunk                      Pineapple-Chunk
                           Red-Cherry-Berry                    Red-Cherry-Berry
...                                                                         ...
Rare Dankness Seeds sativa Ghost-Train-Haze                    Ghost-Train-Haze
                           Moonshine-Haze                        Moonshine-Haze
                           Mother-Tongue                          Mother-Tongue
                           Nevils-Wreck                            Nevils-Wreck
                           Tangerine-Trainwreck-Haze  Tangerine-Trainwreck-Haze

[122 rows x 1 columns]

In [26]:
top5_breeders_count=(OD2["Breeders"].value_counts()[1:6])
top5_breeders_count_df=pd.DataFrame({'breeders':top5_breeders_count.index, 'count':top5_breeders_count.values})
# top5_breeders_count.plot(kind='bar')
top5_breeders_count_df['breeders']

0           DNA Genetics
1     Colorado Seed Inc.
2    Rare Dankness Seeds
3          Barney's Farm
4            Bodhi Seeds
Name: breeders, dtype: object

In [49]:
top50_breeders_count=(OD2["Breeders"].value_counts()[1:51])
top50_breeders_count_df=pd.DataFrame({'breeders':top50_breeders_count.index, 'count':top50_breeders_count.values})
# top5_breeders_count.plot(kind='bar')
top50_breeders_count_df['breeders']

0                                 DNA Genetics
1                           Colorado Seed Inc.
2                          Rare Dankness Seeds
3                                Barney's Farm
4                                  Bodhi Seeds
5                                 TGA Genetics
6                               Exotic Genetix
7                                  Sensi Seeds
8                               Paradise Seeds
9                            Green House Seeds
10                               Dinafem Seeds
11                  Dutch Passion Seed Company
12                                   Ace Seeds
13                                     THSeeds
14                          Archive Seeds Bank
15    Pua Mana 1st Hawaiian Pakal_l_ Seed Bank
16                                  Tikum Olam
17                           AlphaKronic Genes
18                                   MTG Seeds
19                             Flying Dutchman
20                              SinCity Seeds
21                               Nirvana Seeds
22                                Calyx Garden
23                           Soma Sacred Seeds
24                              Mr Nice Seeds
25                                 Cresco Labs
26                       Jordan of the Islands
27                      Canadian LP Tweed, Inc
28                        TGA Subcool Genetics
29                           Royal Queen Seeds
30                                  Sumo Seeds
31                             Elemental Seeds
32                              Alien Genetics
33                                    THClones
34                             Delicious Seeds
35                          Royal Choice Farms
36                             Snow High Seeds
37                       Rebel Spirit Cannabis
38                               Dynasty Seeds
39                          Soulshine Cannabis
40                             Reeferman Seeds
41                          Terraform Genetics
42                         Apothecary Genetics
43                             Cali Connection
44                            Los Angeles Kush
45                               Leaf by Snoop
46                          OG Raskal Genetics
47                           Ocean Grown Seeds
48                                Serious Seed
49                Heroes of the Farm GeneticsÊ
Name: breeders, dtype: object

In [42]:
# # Create a bar chart that shows the count of unique strains grown by the Top 5 Breeders
# color = ['green', 'orange', 'purple', 'red', 'blue']
# ax = top5_breeders_count_df.plot.bar(x='breeders', y='count', legend=False, color=color)

# #annotate bars
# ax.bar_label(ax.containers[0])
# plt.xlabel('Top 5 Breeders')
# plt.ylabel('Unique Strains')
# plt.title('Unique Strains For Top 5 Breeders')
# plt.show()

In [28]:
# Group the top 5 Breeders' by Avg Rating
top5_breeders_avg=top5_breeders_df.groupby("Breeders").Rating.mean()
top5_breeders_avg

NameError: name 'top5_breeders_df' is not defined

In [48]:
# Group the top 50 Breeders' by Avg Rating
top50_breeders_avg=top50_breeders_df.groupby("Breeders").mean()
top50_breeders_avg

NameError: name 'top50_breeders_df' is not defined

In [29]:
# Create a dataframe for the top 5 breeders
top5_breeders_df=OD2.loc[OD2["Breeders"].isin(top5_breeders)]
top5_breeders_df

,Strain,Type,Rating,Effects,Flavor,Breeders,LOCATION,effect_1,effect_2,effect_3,effect_4,effect_5,flavor_1,flavor_2,flavor_3,num_effects,num_flavors
10,501St-Og,hybrid,4.5,"Relaxed,Euphoric,Sleepy,Happy,Talkative","Earthy,Pine,Skunk",Rare Dankness Seeds,Colorado,Relaxed,Euphoric,Sleepy,Happy,Talkative,Earthy,Pine,Skunk,5.0,3.0
13,8-Ball-Kush,indica,4.3,"Relaxed,Uplifted,Happy,Creative,Euphoric","Citrus,Earthy,Pine",Barney's Farm,"Amsterdam, Westmont, Illinois",Relaxed,Uplifted,Happy,Creative,Euphoric,Citrus,Earthy,Pine,5.0,3.0
17,91-Krypt,indica,4.7,"Relaxed,Euphoric,Happy,Hungry,Uplifted","Earthy,Pungent,Berry",DNA Genetics,"Amsterdam,Canada, California",Relaxed,Euphoric,Happy,Hungry,Uplifted,Earthy,Pungent,Berry,5.0,3.0
53,Afternoon-Delight,hybrid,4.8,"Talkative,Relaxed,Uplifted,Tingly,Creative","Pungent,Citrus,Tropical",Colorado Seed Inc.,"Boulder, Colorado",Talkative,Relaxed,Uplifted,Tingly,Creative,Pungent,Citrus,Tropical,5.0,3.0
109,Ancient-Og,indica,4.6,"Relaxed,Euphoric,Sleepy,Happy,Hungry","Earthy,Flowery,Nutty",Bodhi Seeds,"Afghanistan, Hawaii and Nepal",Relaxed,Euphoric,Sleepy,Happy,Hungry,Earthy,Flowery,Nutty,5.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2234,Violator-Kush,indica,4.3,"Relaxed,Sleepy,Happy,Euphoric,Uplifted","Earthy,Spicy/Herbal,Woody",Barney's Farm,"Amsterdam, Westmont, Illinois",Relaxed,Sleepy,Happy,Euphoric,Uplifted,Earthy,Spicy/Herbal,Woody,5.0,3.0
2242,Walker-Kush,hybrid,4.8,"Relaxed,Uplifted,Happy,Focused,Euphoric","Woody,Spicy/Herbal,Flowery",Rare Dankness Seeds,Colorado,Relaxed,Uplifted,Happy,Focused,Euphoric,Woody,Spicy/Herbal,Flowery,5.0,3.0
2286,White-Lotus,hybrid,4.2,"Relaxed,Euphoric,Focused,Happy,Sleepy","Earthy,Citrus,Sweet",Bodhi Seeds,"Afghanistan, Hawaii and Nepal",Relaxed,Euphoric,Focused,Happy,Sleepy,Earthy,Citrus,Sweet,5.0,3.0
2305,White-Walker-Kush,hybrid,4.2,"Happy,Energetic,Uplifted,Euphoric,Creative","Earthy,Sage,Citrus",DNA Genetics,"Amsterdam,Canada, California",Happy,Energetic,Uplifted,Euphoric,Creative,Earthy,Sage,Citrus,5.0,3.0
2322,Wookie,hybrid,5.0,"Talkative,Euphoric,Relaxed","Berry,Earthy,Skunk",Bodhi Seeds,"Afghanistan, Hawaii and Nepal",Talkative,Euphoric,Relaxed,None,None,Berry,Earthy,Skunk,3.0,3.0

In [41]:
# #Found datatypes of top5_breeders
# unique_strain = top5_breeders_df.dtypes[top5_breeders_df.dtypes == 'object'].index.tolist()
# top5_breeders_df[unique_strain].nunique()

In [40]:
# #Sorted breeders by ratings from highest to lowest
# df_sorted_rating = top5_breeders_df.sort_values(['Rating'], ascending=False)
# top5strain = df_sorted_rating[0:5]['Strain'].tolist()
# top5strain

In [39]:
# #Created new dataframe  filtering out top 5 strains and labeling the rest as "other"     
# top5_breeders_df2 = top5_breeders_df.copy()


# filtered_df3 = top5_breeders_df2[top5_breeders_df2['Strain'].isin(top5strain)]

# filtered_df4 = top5_breeders_df2[~top5_breeders_df2['Strain'].isin(top5strain)]
# filtered_df4['Strain'] = 'Others'

# concat_df = pd.concat([filtered_df3,filtered_df4],ignore_index=True)
# concat_df

# X = pd.get_dummies(concat_df,dtype=int)
# X

In [38]:
# #Omit Rating column and then standard scale
# X.drop(columns="Rating")

# from sklearn.datasets import load_iris
# from sklearn.preprocessing import StandardScaler
 
# dataset = load_iris()
# object= StandardScaler()
 
# # Splitting the independent and dependent variables
# i_data = dataset.data
# response = dataset.target
 
# # standardization 
# scale = object.fit_transform(i_data) 
# print(scale)

# #create target variable on y
# Y = pd.concat([concat_df], columns=['Rating'])
# Y

# X_train, Y_train, X_test, Y_test = train_test_splt(X, Y, random_state=1)

In [34]:
top5_breeders

['DNA Genetics',
 'Colorado Seed Inc.',
 'Rare Dankness Seeds',
 "Barney's Farm",
 'Bodhi Seeds']

In [37]:
# # Create Bar Chart Showing the Avg Rating For The Top 5 Breeders 
# color = ['green', 'orange', 'purple', 'red', 'blue']
# ax = top5_breeders_avg.plot.bar(x='breeders', y='rating', legend=False)

# #annotate bars
# ax.bar_label(ax.containers[0])
# plt.xlabel('Top 5 Breeders')
# plt.ylabel('Average Rating')
# plt.title('Average Rating For The Top 5 Breeders')
# color = ['green', 'orange', 'purple', 'red', 'blue']
# plt.show()

In [36]:
breeders_type=top5_breeders_df.groupby(['Breeders','Type'])['Type'].count().unstack()
breeders_type.head()

Type                 hybrid  indica  sativa
Breeders
Barney's Farm             8      12       1
Bodhi Seeds              10       6       3
Colorado Seed Inc.       18       5       3
DNA Genetics             17      10       7
Rare Dankness Seeds       7      10       5